/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class web_action_TestNative */

#ifndef _Included_web_action_TestNative
#define _Included_web_action_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     web_action_TestNative
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_web_action_TestNative_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
